replicaCount: 1

images:
  mosquitto:
    repository: eclipse-mosquitto
    tag: latest
    pullPolicy: IfNotPresent
  tc31:
    repository: flecsbikubernetes.azurecr.io/beckhoff/tc31-mtp
    tag: latest
    pullPolicy: IfNotPresent

service:
  mosquitto:
    type: ClusterIP
    port: 1883
  tc31:
    type: ClusterIP
    ports:
      - name: port2020
        port: 2020
        targetPort: 2020
      - name: port2010
        port: 2010
        targetPort: 2010
      - name: port4840
        port: 4840
        targetPort: 4840

env:
  - name: PCI_DEVICES
    value: 'NONE'

volumes:
  licenseHostPath: ./License/
  mosquittoConfPath: ./simple-mosquitto.conf/simple-mosquitto.conf

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
