replicaCount: 1

images:
  mosquitto:
    repository: eclipse-mosquitto
    tag: latest
    pullPolicy: IfNotPresent
  tc31:
    repository: flecsbikubernetes.azurecr.io/beckhoff/tc31-mtp
    tag: latest
    pullPolicy: IfNotPresent

service:
  mosquitto:
    type: NodePort
    port: 1883 # cluster internal port
    targetPort: 1883 # container target port
    nodePort: 30083 # port opend at k8s node, currently something between 30000-30100
  tc31:
    type: ClusterIP
    ports:
      - name: port2020
        port: 2020
        targetPort: 2020
      - name: port2010
        port: 2010
        targetPort: 2010
      - name: port4840
        port: 4840
        targetPort: 4840

env:
  - name: PCI_DEVICES
    value: 'NONE'

### host path at edge devices is mapped into /volumes-data
volumes:
  licenseHostPath: /volumes-data/beckhoff/license
  # contains e.g.: mosquitto.conf
  mosquittoConfPath: /volumes-data/beckhoff/mosquitto

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
