apiVersion: apps/v1
kind: Deployment
metadata:
  name: tc31-mtp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tc31-mtp
  template:
    metadata:
      labels:
        app: tc31-mtp
    spec:
      containers:
        - name: {{ .Values.nodered.name }}
          image: {{ .Values.nodered.image }}
        - name: mosquitto
          image: "{{ .Values.images.mosquitto.repository }}:{{ .Values.images.mosquitto.tag }}"
          imagePullPolicy: {{ .Values.images.mosquitto.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.mosquitto.port }}
              name: mqtt
              protocol: TCP
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/

        - name: tc31-mtp
          image: "{{ .Values.images.tc31.repository }}:{{ .Values.images.tc31.tag }}"
          imagePullPolicy: {{ .Values.images.tc31.pullPolicy }}
          ports:
            {{- range .Values.service.tc31.ports }}
            - containerPort: {{ .targetPort }}
              name: {{ .name }}
              protocol: TCP
            {{- end }}
          volumeMounts:
            - name: hugepages
              mountPath: /dev/hugepages
              #CHECK mount permisions
            - name: license
              mountPath: /etc/TwinCAT/3.1/Target/License
          env:
            {{- toYaml .Values.env | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: hugepages
          hostPath:
            path: /dev/hugepages
        - name: license
          hostPath:
            path: {{ .Values.volumes.licenseHostPath }}
            type: Directory
        - name: mosquitto-config
          hostPath:
            path: {{ .Values.volumes.mosquittoConfPath }}
            type: Directory
