apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  type: {{ .Values.service.mosquitto.type }}
  selector:
    app: tc31-mtp
  ports:
    - port: {{ .Values.service.mosquitto.port }}
      targetPort: {{ .Values.service.mosquitto.port }}
      protocol: TCP
      name: mqtt

---
apiVersion: v1
kind: Service
metadata:
  name: tc31-mtp
spec:
  type: {{ .Values.service.tc31.type }}
  selector:
    app: tc31-mtp
  ports:
    {{- range .Values.service.tc31.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
    {{- end }}
